version: '3.3'
services:
  server:
    container_name: knitting-helper
    image: joseluisq/static-web-server:2
    ports:
      - "8080:8080"
    volumes:
      - ./dist:/var/public
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik_net"
      - "traefik.http.routers.website.entrypoints=web"
      - "traefik.http.routers.website.rule=Host(`example.com`)"
      - "traefik.http.routers.website.priority=1"
      - "traefik.http.services.website.loadbalancer.server.port=80"
    restart: always
